# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7

pipelines:
  branches:
    master:
      - step:
          name: "Test1 defaut"
          caches:
            - composer
          script:
            - echo "Composer"
            - apt-get update && apt-get install -y unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer require squizlabs/php_codesniffer
            - composer require phploc/phploc
            - composer require friendsofphp/php-cs-fixer
            - composer install
            - echo "phploc"
            - vendor/bin/phploc ./
            #- echo "PHPUnit"
            #- vendor/bin/phpunit
            - echo "Version PHP"
            - php -v
            # Publication d'un nouveau download
            #- curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/output.jar"
            # Creation base MySQL
            #- mysql -h localhost --user=root --password=$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE $MYSQL_DATABASE;"
            #- vendor/bin/phpunit --coverage-clover=coverage.xml
           # - php vendor/bin/phpcs --standard=PSR2 ./
            - php vendor/bin/php-cs-fixer fix --dry-run -v --show-progress=dots ./
            #- php vendor/bin/php-cs-fixer fix ./
          services:
            - mysql
definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: agb
        MYSQL_ROOT_PASSWORD: passroot